/**
 * Regenerates src/icons/icons.ts from the bootstrap-italia SVG set
 * (BSD-3-Clause, https://github.com/italia/bootstrap-italia).
 *   bun run icons
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const pkgDir = dirname(fileURLToPath(import.meta.resolve("bootstrap-italia/package.json")));
const svgDir = join(pkgDir, "src", "svg");

const icons: Record<string, string> = {};
for (const file of readdirSync(svgDir).sort()) {
  if (!file.endsWith(".svg")) continue;
  const raw = readFileSync(join(svgDir, file), "utf8");
  const inner = raw
    .replace(/<\?xml[^>]*>/g, "")
    .replace(/<!--[\s\S]*?-->/g, "")
    .replace(/^[\s\S]*?<svg[^>]*>/, "")
    .replace(/<\/svg>[\s\S]*$/, "")
    .replace(/\s*(fill|style|class|id)="[^"]*"/g, "")
    .replace(/\s+/g, " ")
    .replace(/> </g, "><")
    .trim();
  icons[file.replace(/\.svg$/, "")] = inner;
}

const out =
  `// Generated by scripts/build-icons.ts from bootstrap-italia ${JSON.parse(readFileSync(join(pkgDir, "package.json"), "utf8")).version}. Do not edit.\n` +
  `// Icons: Copyright (c) the bootstrap-italia contributors, BSD-3-Clause.\n` +
  `export const icons = ${JSON.stringify(icons, null, 1)} as const;\n\n` +
  `export type IconName = keyof typeof icons;\n`;

writeFileSync(join(here, "..", "src", "icons", "icons.ts"), out);
console.log(`Wrote ${Object.keys(icons).length} icons`);
